logging:
  path: ${user.home}/logs/springcloud-demo-ch1
  file:
    max-size: 50MB
server:
  port: 8081
  servlet:
    context-path: /springcloud-demo-ch1
spring:
  #main:
    #web-application-type: servlet
  profiles:
    active: dev
debug: false


