server:
  port: 8087
spring:
  application:
    name: eureka8087

eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.251:8083/eureka/,http://192.168.1.252:8083/eureka/
    register-with-eureka: false
    fetch-registry: true
    registry-fetch-interval-seconds: 5

feign:
  hystrix:
    enabled: true