server:
  port: 8085
spring:
  application:
    name: eureka8085

eureka:
  client:
    service-url:
      defaultZone: http://192.168.1.251:8083/eureka/
#  instance:
#    prefer-ip-address: true
#    ip-address: 192.168.1.249
#    hostname: 192.168.1.249
#    appname: service_ch5